before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
aurs:
  -
    name: protoc-gen-rtk-query-bin
    homepage: "https://github.com/greatliontech/protoc-gen-rtk-query"
    description: "Generate rtk-query apis from grpc service definitions"
    license: "MIT"
    private_key: '{{ .Env.AUR_SSH_KEY }}'
    maintainers:
      - 'Nikolas Sepos <nikolas@greatlion.tech>'
    git_url: 'ssh://aur@aur.archlinux.org/protoc-gen-rtk-query-bin.git'
    provides:
      - protoc-gen-rtk-query
    conflicts:
      - protoc-gen-rtk-query
    package: |-
      # bin
      install -Dm755 "./protoc-gen-rtk-query" "${pkgdir}/usr/bin/protoc-gen-rtk-query"
      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/protoc-gen-rtk-query/LICENSE"
    commit_author:
      name: greatbot
      email: bot@greatlion.tech
