package module

const fileTpl = `// Code generated by protoc-gen-rtk-query. DO NOT EDIT.
// source: {{ .file.InputPath }}
{{- $fn := fname .file.Name}}
{{- $fnl := fnamelc .file.Name}}

import { createApi } from '@reduxjs/toolkit/query/react'
import { GrpcWebFetchTransport, GrpcWebOptions } from '@protobuf-ts/grpcweb-transport';
import { grpcBaseQuery, providesList } from '@greatliontech/protobuf-ts-rtk-query';
{{- range .imports}}
{{.}}
{{- end}}

export const grpcWebOptions: GrpcWebOptions = {
  baseUrl: 'http://localhost:8080'
}

const transport = new GrpcWebFetchTransport(grpcWebOptions);

{{- range .file.Services }}
{{- $sn := .Name }}
{{- $snl := .Name.LowerCamelCase }}

const {{$snl}}Client = new {{$sn}}Client(transport)

// Define a service using a base URL and expected endpoints
export const {{$snl}} = createApi({
  reducerPath: '{{$snl}}',
  baseQuery: grpcBaseQuery(),
{{- if hasTags . }}
	tagTypes: {{ tags . }},
{{- end }}
  endpoints: (builder) => ({
{{- range .Methods }}
{{- $mn := .Name }}
{{- $mnl := .Name | lowerFirst }}
    {{$mnl}}: builder.{{if eq (endpoint .) "QUERY"}}query{{else}}mutation{{end}}<{{index $.names .Output.FullyQualifiedName}}, {{index $.names .Input.FullyQualifiedName}}>({
      query: (req) => {{$snl}}Client.{{$mnl}}(req),
{{- if hasProvidesTags . }}
	    providesTags: {{ providesTags . }},
{{- end }}
{{- if hasInvalidatesTags . }}
	    invalidatesTags: {{ invalidatesTags . }},
{{- end }}
    }),
{{- end }}
  }),
})

// Export hooks for usage in function components, which are
// auto-generated based on the defined endpoints
export const {
{{- range .Methods }}
  use{{.Name}}{{if eq (endpoint .) ("QUERY")}}Query{{else}}Mutation{{end}},
{{- end }}
} = {{$snl}}
{{ end }}
`
const storeTpl = `// Code generated by protoc-gen-rtk-query. DO NOT EDIT.
{{ range .Imports }}
{{.}}
{{- end }}

export const apiReducers = {
{{- range .Reducers }}
  {{.}}
{{- end }}
}

export const apiMiddlewares = [
{{- range .Middlewares }}
  {{.}}
{{- end }}
]
`
