# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProtocGenRtkQuery < Formula
  desc "Generate rtk query endpoints from grpc service definitions"
  homepage "https://github.com/greatliontech/protoc-gen-rtk-query"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/greatliontech/protoc-gen-rtk-query/releases/download/0.0.1/protoc-gen-rtk-query_0.0.1_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "d627c97e7c0211201588dbbcaf0f4cc6665197a2f4977c14896e27cd420b9bb2"

      def install
        bin.install "protoc-gen-rtk-query"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/greatliontech/protoc-gen-rtk-query/releases/download/0.0.1/protoc-gen-rtk-query_0.0.1_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "64ae9bd34e1280a9631ebaa7db33e42ce26e0e3422ec69a74310ffb49e0711b7"

      def install
        bin.install "protoc-gen-rtk-query"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/greatliontech/protoc-gen-rtk-query/releases/download/0.0.1/protoc-gen-rtk-query_0.0.1_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "63e2b6dcbcbf91896f818756ea4454146978a521ca1ba1fcd099217297255ebd"

      def install
        bin.install "protoc-gen-rtk-query"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/greatliontech/protoc-gen-rtk-query/releases/download/0.0.1/protoc-gen-rtk-query_0.0.1_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "2c46bc0300472d3c78c20a926ee56133089d553752a1dc2ba67e2443a6a37aa3"

      def install
        bin.install "protoc-gen-rtk-query"
      end
    end
  end
end
