// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: rtkquery/rtkquery.proto

package rtkquerypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EndpointType int32

const (
	EndpointType_QUERY    EndpointType = 0
	EndpointType_MUTATION EndpointType = 1
)

// Enum value maps for EndpointType.
var (
	EndpointType_name = map[int32]string{
		0: "QUERY",
		1: "MUTATION",
	}
	EndpointType_value = map[string]int32{
		"QUERY":    0,
		"MUTATION": 1,
	}
)

func (x EndpointType) Enum() *EndpointType {
	p := new(EndpointType)
	*p = x
	return p
}

func (x EndpointType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EndpointType) Descriptor() protoreflect.EnumDescriptor {
	return file_rtkquery_rtkquery_proto_enumTypes[0].Descriptor()
}

func (EndpointType) Type() protoreflect.EnumType {
	return &file_rtkquery_rtkquery_proto_enumTypes[0]
}

func (x EndpointType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EndpointType.Descriptor instead.
func (EndpointType) EnumDescriptor() ([]byte, []int) {
	return file_rtkquery_rtkquery_proto_rawDescGZIP(), []int{0}
}

type MethodOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EndpointType *EndpointType `protobuf:"varint,1,opt,name=endpoint_type,json=endpointType,proto3,enum=rtkquery.EndpointType,oneof" json:"endpoint_type,omitempty"`
}

func (x *MethodOptions) Reset() {
	*x = MethodOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtkquery_rtkquery_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodOptions) ProtoMessage() {}

func (x *MethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_rtkquery_rtkquery_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodOptions.ProtoReflect.Descriptor instead.
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return file_rtkquery_rtkquery_proto_rawDescGZIP(), []int{0}
}

func (x *MethodOptions) GetEndpointType() EndpointType {
	if x != nil && x.EndpointType != nil {
		return *x.EndpointType
	}
	return EndpointType_QUERY
}

var file_rtkquery_rtkquery_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MethodOptions)(nil),
		Field:         66699,
		Name:          "rtkquery.query",
		Tag:           "bytes,66699,opt,name=query",
		Filename:      "rtkquery/rtkquery.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional rtkquery.MethodOptions query = 66699;
	E_Query = &file_rtkquery_rtkquery_proto_extTypes[0]
)

var File_rtkquery_rtkquery_proto protoreflect.FileDescriptor

var file_rtkquery_rtkquery_proto_rawDesc = []byte{
	0x0a, 0x17, 0x72, 0x74, 0x6b, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2f, 0x72, 0x74, 0x6b, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x74, 0x6b, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x63, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x40, 0x0a, 0x0d, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e,
	0x72, 0x74, 0x6b, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x65, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x27, 0x0a, 0x0c, 0x45, 0x6e,
	0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x51, 0x55,
	0x45, 0x52, 0x59, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x55, 0x54, 0x41, 0x54, 0x49, 0x4f,
	0x4e, 0x10, 0x01, 0x3a, 0x52, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1e, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x8b, 0x89, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x72, 0x74, 0x6b, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x88, 0x01, 0x01, 0x42, 0x49, 0x5a, 0x47, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x72, 0x65, 0x61, 0x74, 0x6c, 0x69, 0x6f, 0x6e, 0x74,
	0x65, 0x63, 0x68, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x72,
	0x74, 0x6b, 0x2d, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72,
	0x74, 0x6b, 0x71, 0x75, 0x65, 0x72, 0x79, 0x3b, 0x72, 0x74, 0x6b, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rtkquery_rtkquery_proto_rawDescOnce sync.Once
	file_rtkquery_rtkquery_proto_rawDescData = file_rtkquery_rtkquery_proto_rawDesc
)

func file_rtkquery_rtkquery_proto_rawDescGZIP() []byte {
	file_rtkquery_rtkquery_proto_rawDescOnce.Do(func() {
		file_rtkquery_rtkquery_proto_rawDescData = protoimpl.X.CompressGZIP(file_rtkquery_rtkquery_proto_rawDescData)
	})
	return file_rtkquery_rtkquery_proto_rawDescData
}

var file_rtkquery_rtkquery_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rtkquery_rtkquery_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rtkquery_rtkquery_proto_goTypes = []interface{}{
	(EndpointType)(0),                  // 0: rtkquery.EndpointType
	(*MethodOptions)(nil),              // 1: rtkquery.MethodOptions
	(*descriptorpb.MethodOptions)(nil), // 2: google.protobuf.MethodOptions
}
var file_rtkquery_rtkquery_proto_depIdxs = []int32{
	0, // 0: rtkquery.MethodOptions.endpoint_type:type_name -> rtkquery.EndpointType
	2, // 1: rtkquery.query:extendee -> google.protobuf.MethodOptions
	1, // 2: rtkquery.query:type_name -> rtkquery.MethodOptions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rtkquery_rtkquery_proto_init() }
func file_rtkquery_rtkquery_proto_init() {
	if File_rtkquery_rtkquery_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rtkquery_rtkquery_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MethodOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_rtkquery_rtkquery_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rtkquery_rtkquery_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_rtkquery_rtkquery_proto_goTypes,
		DependencyIndexes: file_rtkquery_rtkquery_proto_depIdxs,
		EnumInfos:         file_rtkquery_rtkquery_proto_enumTypes,
		MessageInfos:      file_rtkquery_rtkquery_proto_msgTypes,
		ExtensionInfos:    file_rtkquery_rtkquery_proto_extTypes,
	}.Build()
	File_rtkquery_rtkquery_proto = out.File
	file_rtkquery_rtkquery_proto_rawDesc = nil
	file_rtkquery_rtkquery_proto_goTypes = nil
	file_rtkquery_rtkquery_proto_depIdxs = nil
}
