name: build and push buf plugin
on:
  registry_package:
    types: [published]
jobs:
  plugin-release:
    if: ${{ github.event.registry_package.package_version.container_metadata.tag.name != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: setup env
        run: |
          echo "TAG=${{ github.event.registry_package.package_version.container_metadata.tag.name }}" >> $GITHUB_ENV

      - uses: bufbuild/buf-setup-action@v1.27.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: thegrumpylion
          password: ${{ secrets.GLT_PACKAGE_TOKEN }}

      - name: pull the image
        run: |
          docker pull ghcr.io/greatliontech/protoc-gen-rtk-query:${TAG}

      - uses: actions/checkout@v4

      - name: replace buf-plugin version
        run: yq -i ".plugin_version = \"v${TAG}\"" buf.plugin.yaml

      - name: login to BSR
        run: echo ${{secrets.BUF_TOKEN}} | buf registry login --token-stdin --username thegrumpylion

      - name: push buf plugin
        run: |
          buf beta registry plugin push --visibility private --image ghcr.io/greatliontech/protoc-gen-rtk-query:${TAG}
