name: build and push buf plugin
on:
  release:
    types: [published]
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: bufbuild/buf-setup-action@v1.27.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: thegrumpylion
          password: ${{ secrets.GLT_PACKAGE_TOKEN }}

      - name: replace buf-plugin version
        run: yq -i ".plugin_version = \"v${{github.event.release.tag_name}}\"" buf.plugin.yaml

      - name: login to BSR
        run: echo ${{secrets.BUF_TOKEN}} | buf registry login --token-stdin --username thegrumpylion

      - name: push buf plugin
        run: buf beta registry plugin push --visibility public --image ghcr.io/greatliontech/protoc-gen-rtk-query:${{github.event.release.tag_name}}
