name: publish npm
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    -
      uses: actions/setup-node@v3
      with:
        registry-url: https://registry.npmjs.org/
    -
      name: install deps
      run: |
        sudo apt update
        sudo apt install -y moreutils jq
    -
      name: npm publish
      run: |
        cd lib
        jq ".version = \"${GITHUB_REF#"refs/tags/"}\"" package.json | sponge package.json
        npm install
        npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
