name: release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: thegrumpylion
          password: ${{ secrets.GLT_PACKAGE_TOKEN }}

      - uses: go-semantic-release/action@v1
        with:
          allow-initial-development-versions: true
          hooks: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GLT_PACKAGE_TOKEN }}
          AUR_SSH_KEY: ${{ secrets.AUR_SSH_KEY }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
