name: test pr
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: thegrumpylion
          password: ${{ secrets.GLT_PACKAGE_TOKEN }}

      - name: pull the image
        run: |
          TAG=v0.4.4
          VERSION=${TAG#v}
          echo pulling ${VERSION}
          docker pull ghcr.io/greatliontech/protoc-gen-rtk-query:${VERSION}
